#!/bin/bash

BUILD=build_version.h
#
# ephemeral file generated by the build process, whose purpose is
# to include some of the git build info in the binary.
#

git log -1 | head -1 | sed -e 's/commit /\#define GIT_TIP_VERSION "/g' -e 's/$/"\r/g' > ${BUILD}

git log -1 | grep Date | sed -E -e 's/Date:[ ]*/\#define GIT_TIP_DATE "/g' -e 's/$/"\r/g' >> ${BUILD}

if git status | grep 'not staged' >/dev/null; then echo '* With unknown local changes'; else echo 'Caught up' ; fi | sed -e 's/^/\#define GIT_TIP_MSG "/g' -e 's/$/"\r/g' >> ${BUILD}

